# Generated by Django 5.2.4 on 2026-03-08 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="order",
            name="orders_amounts_non_negative_chk",
        ),
        migrations.RemoveConstraint(
            model_name="order",
            name="orders_discount_le_gross_chk",
        ),
        migrations.AddField(
            model_name="order",
            name="canceled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="returned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="source",
            field=models.CharField(blank=True, default="LIVE", max_length=20),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_at", "status"], name="orders_ordered_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_at", "seller"], name="orders_ordered_seller_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_at", "store"], name="orders_ordered_store_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["ordered_at", "channel"], name="orders_ordered_channel_idx"
            ),
        ),
    ]
