# Generated by Django 5.2.4 on 2026-03-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0002_remove_order_orders_amounts_non_negative_chk_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.CharField(max_length=128, unique=True)),
                ("source", models.CharField(blank=True, max_length=50)),
                ("event_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("resource_type", models.CharField(blank=True, max_length=50)),
                ("resource_id", models.CharField(blank=True, max_length=64)),
                ("payload_hash", models.CharField(blank=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("PROCESSED", "Processed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "response_code",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("error_message", models.TextField(blank=True)),
            ],
            options={
                "db_table": "idempotency_keys",
                "indexes": [
                    models.Index(fields=["event_id"], name="idempotency_event_id_idx"),
                    models.Index(fields=["source"], name="idempotency_source_idx"),
                    models.Index(
                        fields=["resource_type", "resource_id"],
                        name="idempotency_resource_idx",
                    ),
                    models.Index(fields=["status"], name="idempotency_status_idx"),
                    models.Index(
                        fields=["processed_at"], name="idempotency_processed_at_idx"
                    ),
                ],
            },
        ),
    ]
